循环命令方块，需要红石。
scoreboard players add step DFS_search 1
连锁命令方块，无条件。
execute as @e[name=DFSSearch] at @s unless block ~1 ~ ~ dirt unless block ~1 ~1 ~ dirt unless block ~1 ~ ~ stone unless block ~1 ~1 ~ stone unless block ~2 ~-1 ~ minecraft:gold_block unless block ~2 ~-1 ~ minecraft:emerald_block unless block ~2 ~-1 ~ minecraft:diamond_block unless block ~2 ~-1 ~ minecraft:redstone_block unless score search_done DFS_search = true DFS_search unless score back DFS_search = true DFS_search if score already_started DFS_search = true DFS_search run setblock ~ ~-1 ~ minecraft:gold_block
execute as @e[name=DFSSearch] at @s if block ~ ~-1 ~ minecraft:gold_block if score back DFS_search = false DFS_search if score search_done DFS_search = false DFS_search run tp @s ~2 ~ ~
execute as @e[name=DFSSearch] at @s unless block ~ ~ ~1 dirt unless block ~ ~1 ~1 dirt unless block ~ ~ ~1 stone unless block ~ ~1 ~1 stone unless block ~ ~-1 ~2 minecraft:gold_block unless block ~ ~-1 ~2 minecraft:emerald_block unless block ~ ~-1 ~2 minecraft:diamond_block unless block ~ ~-1 ~2 minecraft:redstone_block unless score search_done DFS_search = true DFS_search unless score back DFS_search = true DFS_search if score already_started DFS_search = true DFS_search run setblock ~ ~-1 ~ minecraft:gold_block
execute as @e[name=DFSSearch] at @s if block ~ ~-1 ~ minecraft:gold_block if score back DFS_search = false DFS_search if score search_done DFS_search = false DFS_search run tp @s ~ ~ ~2
execute as @e[name=DFSSearch] at @s unless block ~-1 ~ ~ dirt unless block ~-1 ~1 ~ dirt unless block ~-1 ~ ~ stone unless block ~-1 ~1 ~ stone unless block ~-2 ~-1 ~ minecraft:gold_block unless block ~-2 ~-1 ~ minecraft:diamond_block unless block ~-2 ~-1 ~ minecraft:emerald_block unless block ~-2 ~-1 ~ minecraft:redstone_block unless score search_done DFS_search = true DFS_search unless score back DFS_search = true DFS_search if score already_started DFS_search = true DFS_search run setblock ~ ~-1 ~ minecraft:gold_block
execute as @e[name=DFSSearch] at @s if block ~ ~-1 ~ minecraft:gold_block if score back DFS_search = false DFS_search if score search_done DFS_search = false DFS_search run tp @s ~-2 ~ ~
execute as @e[name=DFSSearch] at @s unless block ~ ~ ~-1 dirt unless block ~ ~1 ~-1 dirt unless block ~ ~ ~-1 stone unless block ~ ~1 ~-1 stone unless block ~ ~-1 ~-2 minecraft:gold_block unless block ~ ~-1 ~-2 minecraft:emerald_block unless block ~ ~-1 ~-2 minecraft:diamond_block unless block ~ ~-1 ~-2 minecraft:redstone_block unless score search_done DFS_search = true DFS_search unless score back DFS_search = true DFS_search if score already_started DFS_search = true DFS_search run setblock ~ ~-1 ~ minecraft:gold_block
execute as @e[name=DFSSearch] at @s if block ~ ~-1 ~ minecraft:gold_block if score back DFS_search = false DFS_search if score search_done DFS_search = false DFS_search run tp @s ~ ~ ~-2
execute as @e[name=DFSSearch] at @s unless block ~1 ~ ~ dirt unless block ~1 ~1 ~ dirt unless block ~1 ~ ~ stone unless block ~1 ~1 ~ stone if score already_started DFS_search = false DFS_search if score search_done DFS_search = false DFS_search if block ~ ~-1 ~ minecraft:emerald_block run tp @s ~2 ~ ~
execute as @e[name=DFSSearch] at @s unless block ~ ~ ~1 dirt unless block ~ ~1 ~1 dirt unless block ~ ~ ~1 stone unless block ~ ~1 ~1 stone if score already_started DFS_search = false DFS_search if score search_done DFS_search = false DFS_search if block ~ ~-1 ~ minecraft:emerald_block run tp @s ~ ~ ~2
execute as @e[name=DFSSearch] at @s unless block ~ ~-1 ~ minecraft:emerald_block if score search_done DFS_search = false DFS_search run scoreboard players set already_started DFS_search 1
execute as @e[name=DFSSearch] at @s if score back DFS_search = false DFS_search unless block ~ ~ ~1 air unless block ~ ~1 ~1 air unless block ~-1 ~ ~ air unless block ~-1 ~1 ~ air unless block ~ ~ ~-1 air unless block ~ ~1 ~-1 air if block ~2 ~-1 ~ minecraft:gold_block if score search_done DFS_search = false DFS_search run scoreboard players set back DFS_search 1
execute as @e[name=DFSSearch] at @s if score back DFS_search = false DFS_search unless block ~ ~ ~-1 air unless block ~ ~1 ~-1 air unless block ~-1 ~ ~ air unless block ~-1 ~1 ~ air unless block ~1 ~ ~ air unless block ~1 ~1 ~ air if score search_done DFS_search = false DFS_search if block ~ ~-1 ~2 minecraft:gold_block run scoreboard players set back DFS_search 1
execute as @e[name=DFSSearch] at @s if score back DFS_search = false DFS_search unless block ~ ~ ~1 air unless block ~ ~1 ~1 air unless block ~1 ~ ~ air unless block ~1 ~1 ~ air unless block ~ ~ ~-1 air unless block ~ ~1 ~-1 air if block ~-2 ~-1 ~ minecraft:gold_block if score search_done DFS_search = false DFS_search run scoreboard players set back DFS_search 1
execute as @e[name=DFSSearch] at @s if score back DFS_search = false DFS_search unless block ~ ~ ~1 air unless block ~ ~1 ~1 air unless block ~-1 ~ ~ air unless block ~-1 ~1 ~ air unless block ~1 ~ ~ air unless block ~1 ~1 ~ air if block ~ ~-1 ~-2 minecraft:gold_block if score search_done DFS_search = false DFS_search run scoreboard players set back DFS_search 1
execute if score back DFS_search = true DFS_search run scoreboard players set can_back DFS_search 1
execute as @e[name=DFSSearch] at @s if score can_back DFS_search = true DFS_search if block ~2 ~-1 ~ minecraft:gold_block unless block ~1 ~ ~ stone unless block ~1 ~1 ~ stone unless block ~1 ~ ~ dirt unless block ~1 ~1 ~ dirt if score search_done DFS_search = false DFS_search run setblock ~ ~-1 ~ minecraft:redstone_block
execute as @e[name=DFSSearch] at @s if score can_back DFS_search = true DFS_search if block ~ ~-1 ~ minecraft:redstone_block if score search_done DFS_search = false DFS_search run scoreboard players set can_back DFS_search 0
execute as @e[name=DFSSearch] at @s if score can_back DFS_search = false DFS_search if block ~ ~-1 ~ minecraft:redstone_block if score search_done DFS_search = false DFS_search run tp @s ~2 ~ ~
execute as @e[name=DFSSearch] at @s if score can_back DFS_search = true DFS_search if block ~ ~-1 ~2 minecraft:gold_block unless block ~ ~ ~1 stone unless block ~ ~1 ~1 stone unless block ~ ~ ~1 dirt unless block ~ ~1 ~1 dirt if score search_done DFS_search = false DFS_search run setblock ~ ~-1 ~ minecraft:redstone_block
execute as @e[name=DFSSearch] at @s if score can_back DFS_search = true DFS_search if block ~ ~-1 ~ minecraft:redstone_block if score search_done DFS_search = false DFS_search run scoreboard players set can_back DFS_search 0
execute as @e[name=DFSSearch] at @s if score can_back DFS_search = false DFS_search if block ~ ~-1 ~ minecraft:redstone_block if score search_done DFS_search = false DFS_search run tp @s ~ ~ ~2
execute as @e[name=DFSSearch] at @s if score can_back DFS_search = true DFS_search if block ~-2 ~-1 ~ minecraft:gold_block unless block ~-1 ~ ~ stone unless block ~-1 ~1 ~ stone unless block ~-1 ~ ~ dirt unless block ~-1 ~1 ~ dirt if score search_done DFS_search = false DFS_search run setblock ~ ~-1 ~ minecraft:redstone_block
execute as @e[name=DFSSearch] at @s if score can_back DFS_search = true DFS_search if block ~ ~-1 ~ minecraft:redstone_block if score search_done DFS_search = false DFS_search run scoreboard players set can_back DFS_search 0
execute as @e[name=DFSSearch] at @s if score can_back DFS_search = false DFS_search if block ~ ~-1 ~ minecraft:redstone_block if score search_done DFS_search = false DFS_search run tp @s ~-2 ~ ~
execute as @e[name=DFSSearch] at @s if score can_back DFS_search = true DFS_search if block ~ ~-1 ~-2 minecraft:gold_block unless block ~ ~ ~-1 stone unless block ~ ~1 ~-1 stone unless block ~ ~ ~-1 dirt unless block ~ ~1 ~-1 dirt if score search_done DFS_search = false DFS_search run setblock ~ ~-1 ~ minecraft:redstone_block
execute as @e[name=DFSSearch] at @s if score can_back DFS_search = true DFS_search if block ~ ~-1 ~ minecraft:redstone_block if score search_done DFS_search = false DFS_search run scoreboard players set can_back DFS_search 0
execute as @e[name=DFSSearch] at @s if score can_back DFS_search = false DFS_search if block ~ ~-1 ~ minecraft:redstone_block if score search_done DFS_search = false DFS_search run tp @s ~ ~ ~-2
execute as @e[name=DFSSearch] at @s if score back DFS_search = true DFS_search unless block ~1 ~ ~ stone unless block ~1 ~1 ~ stone unless block ~1 ~ ~ dirt unless block ~1 ~1 ~ dirt unless block ~2 ~-1 ~ minecraft:gold_block unless block ~2 ~-1 ~ minecraft:diamond_block unless block ~2 ~-1 ~ minecraft:redstone_block unless block ~2 ~-1 ~ minecraft:emerald_block if score search_done DFS_search = false DFS_search run scoreboard players set back DFS_search 0
execute as @e[name=DFSSearch] at @s if score back DFS_search = true DFS_search unless block ~ ~ ~1 stone unless block ~ ~1 ~1 stone unless block ~ ~ ~1 dirt unless block ~ ~1 ~1 dirt unless block ~ ~-1 ~2 minecraft:gold_block unless block ~ ~-1 ~2 minecraft:diamond_block unless block ~ ~-1 ~2 minecraft:redstone_block unless block ~ ~-1 ~2 minecraft:emerald_block if score search_done DFS_search = false DFS_search run scoreboard players set back DFS_search 0
execute as @e[name=DFSSearch] at @s if score back DFS_search = true DFS_search unless block ~-1 ~ ~ stone unless block ~-1 ~1 ~ stone unless block ~-1 ~ ~ dirt unless block ~-1 ~1 ~ dirt unless block ~-2 ~-1 ~ minecraft:gold_block unless block ~-2 ~-1 ~ minecraft:diamond_block unless block ~-2 ~-1 ~ minecraft:redstone_block unless block ~-2 ~-1 ~ minecraft:emerald_block if score search_done DFS_search = false DFS_search run scoreboard players set back DFS_search 0
execute as @e[name=DFSSearch] at @s if score back DFS_search = true DFS_search unless block ~ ~ ~-1 stone unless block ~ ~1 ~-1 stone unless block ~ ~ ~-1 dirt unless block ~ ~1 ~-1 dirt unless block ~ ~-1 ~-2 minecraft:gold_block unless block ~ ~-1 ~-2 minecraft:diamond_block unless block ~ ~-1 ~-2 minecraft:redstone_block unless block ~ ~-1 ~-2 minecraft:emerald_block if score search_done DFS_search = false DFS_search run scoreboard players set back DFS_search 0
execute as @e[name=DFSSearch] at @s if score back DFS_search = false DFS_search if block ~ ~-1 ~ minecraft:gold_block run setblock ~ ~-1 ~ minecraft:quartz_block
execute as @e[name=DFSSearch] at @s if block ~2 ~-1 ~ minecraft:diamond_block unless block ~1 ~ ~ stone unless block ~1 ~1 ~ stone unless block ~1 ~ ~ dirt unless block ~1 ~1 ~ dirt run scoreboard players set search_done DFS_search 1
execute as @e[name=DFSSearch] at @s if block ~ ~-1 ~2 minecraft:diamond_block unless block ~ ~ ~1 stone unless block ~ ~1 ~1 stone unless block ~ ~ ~1 dirt unless block ~ ~1 ~1 dirt run scoreboard players set search_done DFS_search 1
execute as @e[name=DFSSearch] at @s if block ~2 ~-1 ~ minecraft:diamond_block unless block ~1 ~ ~ stone unless block ~1 ~1 ~ stone unless block ~1 ~ ~ dirt unless block ~1 ~1 ~ dirt if score search_done DFS_search = true DFS_search run fill ~ ~-1 ~ ~1 ~-1 ~ minecraft:netherite_block
execute as @e[name=DFSSearch] at @s if block ~ ~-1 ~2 minecraft:diamond_block unless block ~ ~ ~1 stone unless block ~ ~1 ~1 stone unless block ~ ~ ~1 dirt unless block ~ ~1 ~1 dirt if score search_done DFS_search = true DFS_search run fill ~ ~-1 ~ ~ ~-1 ~1 minecraft:netherite_block
execute as @e[name=DFSSearch] at @s if block ~2 ~-1 ~ minecraft:gold_block unless block ~1 ~ ~ stone unless block ~1 ~1 ~ stone unless block ~1 ~ ~ dirt unless block ~1 ~1 ~ dirt if score search_done DFS_search = true DFS_search run tp @s ~2 ~ ~
execute as @e[name=DFSSearch] at @s if score search_done DFS_search = true DFS_search if block ~ ~-1 ~ minecraft:gold_block run fill ~ ~-1 ~ ~-1 ~-1 ~ minecraft:netherite_block
execute as @e[name=DFSSearch] at @s if block ~ ~-1 ~2 minecraft:gold_block unless block ~ ~ ~1 stone unless block ~ ~1 ~1 stone unless block ~ ~ ~1 dirt unless block ~ ~1 ~1 dirt if score search_done DFS_search = true DFS_search run tp @s ~ ~ ~2
execute as @e[name=DFSSearch] at @s if score search_done DFS_search = true DFS_search if block ~ ~-1 ~ minecraft:gold_block run fill ~ ~-1 ~ ~ ~-1 ~-1 minecraft:netherite_block
execute as @e[name=DFSSearch] at @s if block ~-2 ~-1 ~ minecraft:gold_block unless block ~-1 ~ ~ stone unless block ~-1 ~1 ~ stone unless block ~-1 ~ ~ dirt unless block ~-1 ~1 ~ dirt if score search_done DFS_search = true DFS_search run tp @s ~-2 ~ ~
execute as @e[name=DFSSearch] at @s if score search_done DFS_search = true DFS_search if block ~ ~-1 ~ minecraft:gold_block run fill ~ ~-1 ~ ~1 ~-1 ~ minecraft:netherite_block
execute as @e[name=DFSSearch] at @s if block ~ ~-1 ~-2 minecraft:gold_block unless block ~ ~ ~-1 stone unless block ~ ~1 ~-1 stone unless block ~ ~ ~-1 dirt unless block ~ ~1 ~-1 dirt if score search_done DFS_search = true DFS_search run tp @s ~ ~ ~-2
execute as @e[name=DFSSearch] at @s if score search_done DFS_search = true DFS_search if block ~ ~-1 ~ minecraft:gold_block run fill ~ ~-1 ~ ~ ~-1 ~1 minecraft:netherite_block
execute as @e[name=DFSSearch] at @s if score search_done DFS_search = true DFS_search if block ~-2 ~-1 ~ minecraft:emerald_block unless block ~-1 ~ ~ stone unless block ~-1 ~1 ~ stone unless block ~-1 ~ ~ dirt unless block ~-1 ~1 ~ dirt run setblock ~-1 ~-1 ~ minecraft:netherite_block
execute as @e[name=DFSSearch] at @s if score search_done DFS_search = true DFS_search if block ~ ~-1 ~-2 minecraft:emerald_block unless block ~ ~ ~-1 stone unless block ~ ~1 ~-1 stone unless block ~ ~ ~-1 dirt unless block ~ ~1 ~-1 dirt run setblock ~ ~-1 ~-1 minecraft:netherite_block
execute as @e[name=DFSSearch] at @s if score search_done DFS_search = true DFS_search if block ~-2 ~-1 ~ minecraft:emerald_block unless block ~-1 ~ ~ stone unless block ~-1 ~1 ~ stone unless block ~-1 ~ ~ dirt unless block ~-1 ~1 ~ dirt run scoreboard players set over DFS_search 1
execute as @e[name=DFSSearch] at @s if score search_done DFS_search = true DFS_search if block ~ ~-1 ~-2 minecraft:emerald_block unless block ~ ~ ~-1 stone unless block ~ ~1 ~-1 stone unless block ~ ~ ~-1 dirt unless block ~ ~1 ~-1 dirt run scoreboard players set over DFS_search 1
execute as @e[name=DFSSearch] at @s if score over DFS_search = true DFS_search run tp @s 3 5 8
execute if score over DFS_search = true DFS_search run tellraw @a {"color":"gold","text":"[DFS迷宫搜索]路径已找到，已使用下界合金块标出！"}
execute if score over DFS_search = true DFS_search run fill 1 4 6 103 4 108 minecraft:quartz_block replace minecraft:gold_block
execute if score over DFS_search = true DFS_search run fill 1 4 6 103 4 108 minecraft:quartz_block replace minecraft:redstone_block
execute if score over DFS_search = true DFS_search run setblock 5 5 -4 minecraft:lever[powered=false,facing=east,face=floor]